/* Generated by scripts/build-print.mjs at 2026-05-10T17:37:23.505Z */
export type PrintImage = { filename: string; caption?: string; credit?: string; alt: string };

export const printImages: {
  cover: PrintImage;
  frontispiece: PrintImage;
  chapters: Record<string, PrintImage>;
  supporting: Record<string, PrintImage[]>;
  closing: PrintImage;
} = {
  cover: { filename: "cover.jpg", alt: "Cover image" },
  frontispiece: { filename: "frontispiece.jpg", alt: "Frontispiece image" },
  chapters: {
    "01-reality-of-ownership": { filename: "ch01.jpg", alt: "Chapter 01 opener" },
    "02-reading-the-market": { filename: "ch02.jpg", alt: "Chapter 02 opener" },
    "03-how-the-industry-works": { filename: "ch03.jpg", alt: "Chapter 03 opener" },
    "04-acquisition-process": { filename: "ch04.jpg", alt: "Chapter 04 opener" },
    "05-new-build-versus-brokerage": { filename: "ch05.jpg", alt: "Chapter 05 opener" },
    "06-refit": { filename: "ch06.jpg", alt: "Chapter 06 opener" },
    "07-operations": { filename: "ch07.jpg", alt: "Chapter 07 opener" },
    "08-motor-versus-sail": { filename: "ch08.jpg", alt: "Chapter 08 opener" },
    "09-decision-framework": { filename: "ch09.jpg", alt: "Chapter 09 opener" },
  },
  supporting: {
    "01-reality-of-ownership": [{ filename: "ch01-sup1.jpg", alt: "Chapter 01 supporting" }],
    "02-reading-the-market": [{ filename: "ch02-sup1.jpg", alt: "Chapter 02 supporting" }, { filename: "ch02-sup2.jpg", alt: "Chapter 02 supporting" }],
    "03-how-the-industry-works": [{ filename: "ch03-sup1.jpg", alt: "Chapter 03 supporting" }],
    "04-acquisition-process": [{ filename: "ch04-sup1.jpg", alt: "Chapter 04 supporting" }],
    "05-new-build-versus-brokerage": [{ filename: "ch05-sup1.jpg", alt: "Chapter 05 supporting" }],
    "06-refit": [{ filename: "ch06-sup1.jpg", alt: "Chapter 06 supporting" }],
    "07-operations": [{ filename: "ch07-sup1.jpg", alt: "Chapter 07 supporting" }, { filename: "ch07-sup2.jpg", alt: "Chapter 07 supporting" }],
    "08-motor-versus-sail": [{ filename: "ch08-sup1.jpg", alt: "Chapter 08 supporting" }],
    "09-decision-framework": [{ filename: "ch09-sup1.jpg", alt: "Chapter 09 supporting" }],
  },
  closing: { filename: "closing.jpg", alt: "Closing image" },
};
