/* Extended 2026-08-08: heavy-imagery pass. Supporting pool grown to four
   per chapter, plus a tall (two-thirds-page) figure and a case-study
   image per chapter, curated from the Foreland stock library. */
export type PrintImage = { filename: string; caption?: string; credit?: string; alt: string };

export const printImages: {
  cover: PrintImage;
  frontispiece: PrintImage;
  chapters: Record<string, PrintImage>;
  supporting: Record<string, PrintImage[]>;
  /* Full-page plates. Printed standalone and merged over a placeholder in
     the flow, the same mechanism as the chapter openers, because Chrome
     fragments a mid-document full-page box against the root master and
     paints a seam. Two per chapter. */
  plates: Record<string, PrintImage[]>;
  tall: Record<string, PrintImage>;
  cases: Record<string, PrintImage>;
  closing: PrintImage;
} = {
  cover: { filename: "cover.jpg", alt: "Cover image" },
  frontispiece: { filename: "frontispiece.jpg", alt: "Frontispiece image" },
  chapters: {
    "01-reality-of-ownership": { filename: "ch01.jpg", alt: "Chapter 01 opener" },
    "02-reading-the-market": { filename: "ch02.jpg", alt: "Chapter 02 opener" },
    "03-how-the-industry-works": { filename: "ch03.jpg", alt: "Chapter 03 opener" },
    "04-acquisition-process": { filename: "ch04.jpg", alt: "Chapter 04 opener" },
    "05-new-build-versus-brokerage": { filename: "ch05.jpg", alt: "Chapter 05 opener" },
    "06-refit": { filename: "ch06.jpg", alt: "Chapter 06 opener" },
    "07-operations": { filename: "ch07.jpg", alt: "Chapter 07 opener" },
    "08-motor-versus-sail": { filename: "ch08.jpg", alt: "Chapter 08 opener" },
    "09-decision-framework": { filename: "ch09.jpg", alt: "Chapter 09 opener" },
  },
  supporting: {
    "01-reality-of-ownership": [
      { filename: "ch01-sup1.jpg", alt: "Chapter 01 supporting" },
      { filename: "ch01-sup2.jpg", alt: "Owner seated on the bow" },
      { filename: "ch01-sup3.jpg", alt: "Guest deck at anchor" },
      { filename: "ch01-sup4.jpg", alt: "Tender cockpit detail" },
      { filename: "40023942-edbc-4252-a8aa-43d36b870752.jpg", alt: "Supporting photograph, chapter 01" },
      { filename: "aleksandr-skvortsov-ykSc4VaRtBQ-unsplash.jpg", alt: "Supporting photograph, chapter 01" },
      { filename: "aristos-aristidou-Rj3gpDWNnAQ-unsplash.jpg", alt: "Supporting photograph, chapter 01" },
      { filename: "brandon-hoogenboom-3ZFbnY2jXlg-unsplash.jpg", alt: "Supporting photograph, chapter 01" },
      { filename: "clem-onojeghuo-2ig6PO_LKTo-unsplash.jpg", alt: "Supporting photograph, chapter 01" },
      { filename: "dmitrii-e-sWCmHYAWUvc-unsplash.jpg", alt: "Supporting photograph, chapter 01" },
      { filename: "filip-steficar-dH-iDh8fmwk-unsplash.jpg", alt: "Supporting photograph, chapter 01" },
      { filename: "getty-images-EJs9wfuoNxI-unsplash.jpg", alt: "Supporting photograph, chapter 01" },
      { filename: "giulia-squillace-K_63dcjyfRE-unsplash.jpg", alt: "Supporting photograph, chapter 01" },
      { filename: "irfan-syahmi-_ZHo_ltt1oo-unsplash.jpg", alt: "Supporting photograph, chapter 01" },
      { filename: "julia-taubitz-zAMUHlvftHA-unsplash.jpg", alt: "Supporting photograph, chapter 01" },
      { filename: "kateryna-hliznitsova-hm6BJObFpMI-unsplash.jpg", alt: "Supporting photograph, chapter 01" },
      { filename: "leo-talabardon-KfTUI-1TOuU-unsplash.jpg", alt: "Supporting photograph, chapter 01" },
      { filename: "lidija-jakovljevic-QC9gI4_jfTY-unsplash.jpg", alt: "Supporting photograph, chapter 01" },
      { filename: "mathias-reding-r1svwWcQif4-unsplash.jpg", alt: "Supporting photograph, chapter 01" },
      { filename: "nathan-anderson-SENyJWI9Za4-unsplash.jpg", alt: "Supporting photograph, chapter 01" },
      { filename: "peter-thomas-QtWL3xp-Hto-unsplash.jpg", alt: "Supporting photograph, chapter 01" },
      { filename: "riccardo-simoneschi-x7LGm8OVb0I-unsplash.jpg", alt: "Supporting photograph, chapter 01" },
    ],
    "02-reading-the-market": [
      { filename: "ch02-sup1.jpg", alt: "Chapter 02 supporting" },
      { filename: "ch02-sup2.jpg", alt: "Marina pontoons from above" },
      { filename: "ch02-sup3.jpg", alt: "Monaco marina" },
      { filename: "ch02-sup4.jpg", alt: "Harbour at dusk" },
      { filename: "50m-above-bWiocb-XhyA-unsplash.jpg", alt: "Supporting photograph, chapter 02" },
      { filename: "alexander-mils-l4-oK4lbKQ0-unsplash.jpg", alt: "Supporting photograph, chapter 02" },
      { filename: "armin-pfarr-lXwXqgIUFTg-unsplash.jpg", alt: "Supporting photograph, chapter 02" },
      { filename: "bruno-ngarukiye-pgiWBkvA5UA-unsplash.jpg", alt: "Supporting photograph, chapter 02" },
      { filename: "craig-cameron-J7wc9brCLBs-unsplash.jpg", alt: "Supporting photograph, chapter 02" },
      { filename: "dorin-seremet-TaBBR57-KO4-unsplash.jpg", alt: "Supporting photograph, chapter 02" },
      { filename: "foto-k-fdmnBIEsKYc-unsplash.jpg", alt: "Supporting photograph, chapter 02" },
      { filename: "getty-images-Wq-iZ8Y0EL4-unsplash.jpg", alt: "Supporting photograph, chapter 02" },
      { filename: "haberdoedas-7-zdywEuYHw-unsplash.jpg", alt: "Supporting photograph, chapter 02" },
      { filename: "isaac-wolff-nHRx6FWokVg-unsplash.jpg", alt: "Supporting photograph, chapter 02" },
      { filename: "kaleb-duperre-gGML8QtQ614-unsplash.jpg", alt: "Supporting photograph, chapter 02" },
      { filename: "kateryna-hliznitsova-nMo_EkEtYlM-unsplash.jpg", alt: "Supporting photograph, chapter 02" },
      { filename: "leo-talabardon-Yfu0TL31MEQ-unsplash.jpg", alt: "Supporting photograph, chapter 02" },
      { filename: "liliia-j6fci9v6w4M-unsplash.jpg", alt: "Supporting photograph, chapter 02" },
      { filename: "maurits-bausenhart-hAtm9G3TPR0-unsplash.jpg", alt: "Supporting photograph, chapter 02" },
      { filename: "nathan-anderson-SiYSjv3aL20-unsplash.jpg", alt: "Supporting photograph, chapter 02" },
      { filename: "philip-myrtorp-0Ey6I4c19PA-unsplash.jpg", alt: "Supporting photograph, chapter 02" },
      { filename: "robin-the-bird-fAcUBsqk3-k-unsplash.jpg", alt: "Supporting photograph, chapter 02" },
    ],
    "03-how-the-industry-works": [
      { filename: "ch03-sup1.jpg", alt: "Chapter 03 supporting" },
      { filename: "ch03-sup2.jpg", alt: "Boat show pontoons" },
      { filename: "ch03-sup3.jpg", alt: "Brokerage quay" },
      { filename: "ch03-sup4.jpg", alt: "Superyacht in city waters" },
      { filename: "IMG_0263.jpg", alt: "Supporting photograph, chapter 03" },
      { filename: "alexandros-giannakakis-kGdAphiYwy4-unsplash.jpg", alt: "Supporting photograph, chapter 03" },
      { filename: "arno-senoner-1q7RE0CXstU-unsplash.jpg", alt: "Supporting photograph, chapter 03" },
      { filename: "bugra-karacam-937irsSMhug-unsplash.jpg", alt: "Supporting photograph, chapter 03" },
      { filename: "curated-lifestyle-xb7EPBgbgLA-unsplash.jpg", alt: "Supporting photograph, chapter 03" },
      { filename: "e2aa6ba5-abc9-43d3-b69d-b299a1d43938.jpg", alt: "Supporting photograph, chapter 03" },
      { filename: "francisco-gomes-DDyl_mkjqmg-unsplash.jpg", alt: "Supporting photograph, chapter 03" },
      { filename: "getty-images-etp5O4aQc7E-unsplash.jpg", alt: "Supporting photograph, chapter 03" },
      { filename: "hassan-nizam-Y3Hbh7wB8CI-unsplash.jpg", alt: "Supporting photograph, chapter 03" },
      { filename: "jack-bell-suRQRuFexWI-unsplash.jpg", alt: "Supporting photograph, chapter 03" },
      { filename: "karl-muscat-8S9DC-GerN0-unsplash.jpg", alt: "Supporting photograph, chapter 03" },
      { filename: "kateryna-hliznitsova-zSm1qBjYDcQ-unsplash.jpg", alt: "Supporting photograph, chapter 03" },
      { filename: "leo-talabardon-eSexneYlxI4-unsplash.jpg", alt: "Supporting photograph, chapter 03" },
      { filename: "lukas-neu-7RtHe6pU5lo-unsplash.jpg", alt: "Supporting photograph, chapter 03" },
      { filename: "maurits-bausenhart-v-5m2uAzhYM-unsplash.jpg", alt: "Supporting photograph, chapter 03" },
      { filename: "navy-medicine-ExR99gl00gY-unsplash.jpg", alt: "Supporting photograph, chapter 03" },
      { filename: "phillip-waterton-H1P6hkQLSGk-unsplash.jpg", alt: "Supporting photograph, chapter 03" },
      { filename: "robin-van-bienen-swDzpjv9zuM-unsplash.jpg", alt: "Supporting photograph, chapter 03" },
    ],
    "04-acquisition-process": [
      { filename: "ch04-sup1.jpg", alt: "Chapter 04 supporting" },
      { filename: "ch04-sup2.jpg", alt: "Navigation instruments" },
      { filename: "ch04-sup3.jpg", alt: "Compass binnacle" },
      { filename: "ch04-sup4.jpg", alt: "Helm and instruments" },
      { filename: "IMG_0646.jpg", alt: "Supporting photograph, chapter 04" },
      { filename: "alexandros-giannakakis-z5lGREDnrCY-unsplash.jpg", alt: "Supporting photograph, chapter 04" },
      { filename: "arno-senoner-iOmFn_anJvA-unsplash.jpg", alt: "Supporting photograph, chapter 04" },
      { filename: "c06ec634-4bd8-448a-a8f3-678cb0b5aa6e.jpg", alt: "Supporting photograph, chapter 04" },
      { filename: "danilo-capece-Mn5vLHPLTuw-unsplash.jpg", alt: "Supporting photograph, chapter 04" },
      { filename: "egor-myznik--9CtCCFQJyM-unsplash.jpg", alt: "Supporting photograph, chapter 04" },
      { filename: "francisco-gomes-nSmCeE_0ioU-unsplash.jpg", alt: "Supporting photograph, chapter 04" },
      { filename: "getty-images-j1TSbzSHpu4-unsplash.jpg", alt: "Supporting photograph, chapter 04" },
      { filename: "howard-r-wheeler-l9IO5bgpz6w-unsplash.jpg", alt: "Supporting photograph, chapter 04" },
      { filename: "jamie-morrison-aOXXCpLoQz0-unsplash.jpg", alt: "Supporting photograph, chapter 04" },
      { filename: "karl-muscat-Pc85Zbj9K1Y-unsplash.jpg", alt: "Supporting photograph, chapter 04" },
      { filename: "katja-ano--dGT6BlPwNQ-unsplash.jpg", alt: "Supporting photograph, chapter 04" },
      { filename: "leo-talabardon-kWIQqUw_Do4-unsplash.jpg", alt: "Supporting photograph, chapter 04" },
      { filename: "m-r-KwwAe7QVQSk-unsplash.jpg", alt: "Supporting photograph, chapter 04" },
      { filename: "michael-WFg0H8V2560-unsplash.jpg", alt: "Supporting photograph, chapter 04" },
      { filename: "nguyen-dang-hoang-nhu-QIxlc7LRRO0-unsplash.jpg", alt: "Supporting photograph, chapter 04" },
      { filename: "plane-jetbridge-night.jpg", alt: "Supporting photograph, chapter 04" },
      { filename: "royce-fonseca-EvbI6IGEzzI-unsplash.jpg", alt: "Supporting photograph, chapter 04" },
    ],
    "05-new-build-versus-brokerage": [
      { filename: "ch05-sup1.jpg", alt: "Chapter 05 supporting" },
      { filename: "ch05-sup2.jpg", alt: "Yard logistics" },
      { filename: "ch05-sup3.jpg", alt: "Shipyard pier" },
      { filename: "ch05-sup4.jpg", alt: "Hull planking work" },
      { filename: "IMG_9616.jpg", alt: "Supporting photograph, chapter 05" },
      { filename: "alexandros-sarakasidis-iXUx8yyE8J0-unsplash.jpg", alt: "Supporting photograph, chapter 05" },
      { filename: "arno-senoner-loU_6fwdPRc-unsplash.jpg", alt: "Supporting photograph, chapter 05" },
      { filename: "catrin-ellis-6ZFkJeq_KNY-unsplash.jpg", alt: "Supporting photograph, chapter 05" },
      { filename: "davide-baraldi-Uib7XdG5s50-unsplash.jpg", alt: "Supporting photograph, chapter 05" },
      { filename: "elin-tabitha-GYsPG2JjcmY-unsplash.jpg", alt: "Supporting photograph, chapter 05" },
      { filename: "freysteinn-g-jonsson-RhiSGdkk664-unsplash.jpg", alt: "Supporting photograph, chapter 05" },
      { filename: "getty-images-n54yNBA7wuU-unsplash.jpg", alt: "Supporting photograph, chapter 05" },
      { filename: "ian-keefe-o51ZmPzv95Q-unsplash.jpg", alt: "Supporting photograph, chapter 05" },
      { filename: "jan-rojas-bPMpJC8tFSA-unsplash.jpg", alt: "Supporting photograph, chapter 05" },
      { filename: "karl-paul-baldacchino-sWzRTyObW5Y-unsplash.jpg", alt: "Supporting photograph, chapter 05" },
      { filename: "kevs-XWNbUhUINB8-unsplash.jpg", alt: "Supporting photograph, chapter 05" },
      { filename: "leo-talabardon-q7R50TejBHw-unsplash.jpg", alt: "Supporting photograph, chapter 05" },
      { filename: "mael-balland-osTXbFNtu5I-unsplash.jpg", alt: "Supporting photograph, chapter 05" },
      { filename: "michal-parzuchowski-sc20oy3G_JU-unsplash.jpg", alt: "Supporting photograph, chapter 05" },
      { filename: "noah-kocherhans-asvLaFreJI0-unsplash.jpg", alt: "Supporting photograph, chapter 05" },
      { filename: "rachel-c-G5GNy-W2CN0-unsplash.jpg", alt: "Supporting photograph, chapter 05" },
      { filename: "royce-fonseca-FGqBGp-TgUk-unsplash.jpg", alt: "Supporting photograph, chapter 05" },
    ],
    "06-refit": [
      { filename: "ch06-sup1.jpg", alt: "Chapter 06 supporting" },
      { filename: "ch06-sup2.jpg", alt: "Machine shop" },
      { filename: "ch06-sup3.jpg", alt: "Yachts under refit cover" },
      { filename: "ch06-sup4.jpg", alt: "Engine room" },
      { filename: "YAW275.ssw_jclass.st_barths_bucket17cb_06172_retouch.jpg", alt: "Supporting photograph, chapter 06" },
      { filename: "amit-adler-o-GUkfq0tlE-unsplash.jpg", alt: "Supporting photograph, chapter 06" },
      { filename: "atul-ajit-Lvr-U5Bpdqs-unsplash.jpg", alt: "Supporting photograph, chapter 06" },
      { filename: "cheyenne-martinez-fxWgrrY9Pb8-unsplash.jpg", alt: "Supporting photograph, chapter 06" },
      { filename: "dawid-tkocz-uMC90Hs4iRw-unsplash.jpg", alt: "Supporting photograph, chapter 06" },
      { filename: "elisa-amadori-x697Tj0MQ80-unsplash.jpg", alt: "Supporting photograph, chapter 06" },
      { filename: "geio-tischler-zTiYT7HHzAE-unsplash.jpg", alt: "Supporting photograph, chapter 06" },
      { filename: "getty-images-nSAVfaBOJg4-unsplash.jpg", alt: "Supporting photograph, chapter 06" },
      { filename: "ian-oQFYNx4y1Vc-unsplash.jpg", alt: "Supporting photograph, chapter 06" },
      { filename: "jo-rhn-ScDWFq-d0aE-unsplash.jpg", alt: "Supporting photograph, chapter 06" },
      { filename: "karsh-mehta-lzHT7mlT500-unsplash.jpg", alt: "Supporting photograph, chapter 06" },
      { filename: "kirsty-iPjaeaNq8Jw-unsplash.jpg", alt: "Supporting photograph, chapter 06" },
      { filename: "leon-bredella-SacHhp1_6_U-unsplash.jpg", alt: "Supporting photograph, chapter 06" },
      { filename: "maksim-shutov-Lkdjnzmz0PY-unsplash.jpg", alt: "Supporting photograph, chapter 06" },
      { filename: "miljan-mijatovic-0v2J60JC_MA-unsplash.jpg", alt: "Supporting photograph, chapter 06" },
      { filename: "oliver-hayes-bXDQl_36JsE-unsplash.jpg", alt: "Supporting photograph, chapter 06" },
      { filename: "rafael-garcin-_Fm0Td2k6sI-unsplash.jpg", alt: "Supporting photograph, chapter 06" },
      { filename: "royce-fonseca-Idzjyp9GA58-unsplash.jpg", alt: "Supporting photograph, chapter 06" },
    ],
    "07-operations": [
      { filename: "ch07-sup1.jpg", alt: "Chapter 07 supporting" },
      { filename: "ch07-sup2.jpg", alt: "Crew at work on deck" },
      { filename: "ch07-sup3.jpg", alt: "Bridge operations" },
      { filename: "ch07-sup4.jpg", alt: "Night passage on the bridge" },
      { filename: "aaron-burden-oHNzEstWRec-unsplash.jpg", alt: "Supporting photograph, chapter 07" },
      { filename: "andras-joo-5LK8T0pjPZc-unsplash.jpg", alt: "Supporting photograph, chapter 07" },
      { filename: "ben-elliott-qdrmRHrCmTk-unsplash.jpg", alt: "Supporting photograph, chapter 07" },
      { filename: "chris-jones-KRTKf7Ogps0-unsplash.jpg", alt: "Supporting photograph, chapter 07" },
      { filename: "deco-fernandes-S19oQp2-Imw-unsplash.jpg", alt: "Supporting photograph, chapter 07" },
      { filename: "erik-seth-snoX2DPdVE0-unsplash.jpg", alt: "Supporting photograph, chapter 07" },
      { filename: "getty-images-2SLopmIhuYY-unsplash.jpg", alt: "Supporting photograph, chapter 07" },
      { filename: "getty-images-rCTUUqtaaQE-unsplash.jpg", alt: "Supporting photograph, chapter 07" },
      { filename: "ibrahim-boran-XdIrwH98K_E-unsplash.jpg", alt: "Supporting photograph, chapter 07" },
      { filename: "john-murphey-zrhXiZz74qw-unsplash.jpg", alt: "Supporting photograph, chapter 07" },
      { filename: "kateryna-hliznitsova-2Ccv7o1a0UQ-unsplash.jpg", alt: "Supporting photograph, chapter 07" },
      { filename: "lakshmi-narasimha-lk7fFQnPMrM-unsplash.jpg", alt: "Supporting photograph, chapter 07" },
      { filename: "lidija-jakovljevic-0GLW9fxMYQc-unsplash.jpg", alt: "Supporting photograph, chapter 07" },
      { filename: "marina-night.jpg", alt: "Supporting photograph, chapter 07" },
      { filename: "moniek-van-rosse-3thEYqTQ44M-unsplash.jpg", alt: "Supporting photograph, chapter 07" },
      { filename: "ozren-cuculic-L2KW_vFe20g-unsplash.jpg", alt: "Supporting photograph, chapter 07" },
      { filename: "raimond-klavins-tkyS5gsATxw-unsplash.jpg", alt: "Supporting photograph, chapter 07" },
      { filename: "royce-fonseca-bU7vLOtG-W0-unsplash.jpg", alt: "Supporting photograph, chapter 07" },
    ],
    "08-motor-versus-sail": [
      { filename: "ch08-sup1.jpg", alt: "Chapter 08 supporting" },
      { filename: "ch08-sup2.jpg", alt: "J Class yachts racing" },
      { filename: "ch08-sup3.jpg", alt: "Sailing yacht at sunset" },
      { filename: "ch08-sup4.jpg", alt: "Motor yacht under way" },
      { filename: "adam-bignell-YRXjbaQAJso-unsplash.jpg", alt: "Supporting photograph, chapter 08" },
      { filename: "andre-tan-4DRfdkajOq8-unsplash.jpg", alt: "Supporting photograph, chapter 08" },
      { filename: "boris-misevic-ZUlV60gfNJI-unsplash.jpg", alt: "Supporting photograph, chapter 08" },
      { filename: "christian-lambert-P8O2cZEhUXE-unsplash.jpg", alt: "Supporting photograph, chapter 08" },
      { filename: "dima-pima-Vc9SsoEZfGw-unsplash.jpg", alt: "Supporting photograph, chapter 08" },
      { filename: "erin-doering-S4q7EkDPUBU-unsplash.jpg", alt: "Supporting photograph, chapter 08" },
      { filename: "getty-images-7C0QX45Pt8Q-unsplash.jpg", alt: "Supporting photograph, chapter 08" },
      { filename: "getty-images-rehAAfNF-xs-unsplash.jpg", alt: "Supporting photograph, chapter 08" },
      { filename: "ibrahim-boran-asiJSIcFlBE-unsplash.jpg", alt: "Supporting photograph, chapter 08" },
      { filename: "johnny-such-yDUnJ7EHCas-unsplash.jpg", alt: "Supporting photograph, chapter 08" },
      { filename: "kateryna-hliznitsova-FWA1DfzRq-A-unsplash.jpg", alt: "Supporting photograph, chapter 08" },
      { filename: "lazarescu-alexandra-I9XxRhaU6Ok-unsplash.jpg", alt: "Supporting photograph, chapter 08" },
      { filename: "lidija-jakovljevic-C7u0AvLrnOU-unsplash.jpg", alt: "Supporting photograph, chapter 08" },
      { filename: "mariola-grobelska-HY8CvkrAdDw-unsplash.jpg", alt: "Supporting photograph, chapter 08" },
      { filename: "muhammed-fardeen-finos-GYLIyRHzeMg-unsplash.jpg", alt: "Supporting photograph, chapter 08" },
      { filename: "pablo-ceas-Gzs4n8QB3Pk-unsplash.jpg", alt: "Supporting photograph, chapter 08" },
      { filename: "redcharlie-QFlD2f7E0i4-unsplash.jpg", alt: "Supporting photograph, chapter 08" },
      { filename: "royce-fonseca-zIQn8KeqOyg-unsplash.jpg", alt: "Supporting photograph, chapter 08" },
    ],
    "09-decision-framework": [
      { filename: "ch09-sup1.jpg", alt: "Chapter 09 supporting" },
      { filename: "ch09-sup2.jpg", alt: "Lone sail on open water" },
      { filename: "ch09-sup3.jpg", alt: "Yacht at anchor in a quiet bay" },
      { filename: "ch09-sup4.jpg", alt: "Yacht in monochrome" },
      { filename: "alberto-bianchini-qLfaGkKqY-E-unsplash.jpg", alt: "Supporting photograph, chapter 09" },
      { filename: "andrea-zignin-Us8dszDXx28-unsplash.jpg", alt: "Supporting photograph, chapter 09" },
      { filename: "boris-misevic-q_8cRkqTWNk-unsplash.jpg", alt: "Supporting photograph, chapter 09" },
      { filename: "christina-victoria-craft-6UfUGat_b9o-unsplash.jpg", alt: "Supporting photograph, chapter 09" },
      { filename: "dmitrii-e-1qnR6rP7W20-unsplash.jpg", alt: "Supporting photograph, chapter 09" },
      { filename: "farnaz-kohankhaki-RuZyXuTcxjU-unsplash.jpg", alt: "Supporting photograph, chapter 09" },
      { filename: "getty-images-8kxn2mJnCHs-unsplash.jpg", alt: "Supporting photograph, chapter 09" },
      { filename: "giu-vicente-zRVAp_RxNZA-unsplash.jpg", alt: "Supporting photograph, chapter 09" },
      { filename: "ilyuza-mingazova-EP0bBbVrAvw-unsplash.jpg", alt: "Supporting photograph, chapter 09" },
      { filename: "julia-fiander-f3MpF2p8s5Y-unsplash.jpg", alt: "Supporting photograph, chapter 09" },
      { filename: "kateryna-hliznitsova-UbNP8ygsNTw-unsplash.jpg", alt: "Supporting photograph, chapter 09" },
      { filename: "leo-talabardon-F9CdiSYF9Ys-unsplash.jpg", alt: "Supporting photograph, chapter 09" },
      { filename: "lidija-jakovljevic-OkHsDzlyyxM-unsplash.jpg", alt: "Supporting photograph, chapter 09" },
      { filename: "mathias-reding-jzh2M31JKJQ-unsplash.jpg", alt: "Supporting photograph, chapter 09" },
      { filename: "muhammed-fardeen-finos-YKwpq3BtLZs-unsplash.jpg", alt: "Supporting photograph, chapter 09" },
      { filename: "parej-richard--wxEqHRikeE-unsplash.jpg", alt: "Supporting photograph, chapter 09" },
      { filename: "renan-brun-ohz-mXxGpUw-unsplash.jpg", alt: "Supporting photograph, chapter 09" },
      { filename: "satchymo-photos-mlpYtVy8iOM-unsplash.jpg", alt: "Supporting photograph, chapter 09" },
    ],
  },
  tall: {
    "01-reality-of-ownership": { filename: "ch01-tall.jpg", alt: "Owner and child on deck" },
    "02-reading-the-market": { filename: "ch02-tall.jpg", alt: "Marina masts at night" },
    "03-how-the-industry-works": { filename: "ch03-tall.jpg", alt: "Bow from below" },
    "04-acquisition-process": { filename: "ch04-tall.jpg", alt: "Mast against the sky" },
    "05-new-build-versus-brokerage": { filename: "ch05-tall.jpg", alt: "Yacht and yard crane" },
    "06-refit": { filename: "ch06-tall.jpg", alt: "Machinery space" },
    "07-operations": { filename: "ch07-tall.jpg", alt: "Captain portrait" },
    "08-motor-versus-sail": { filename: "ch08-tall.jpg", alt: "Sails in monochrome" },
    "09-decision-framework": { filename: "ch09-tall.jpg", alt: "Yacht from above" },
  },
  cases: {
    "01-reality-of-ownership": { filename: "ch01-case.jpg", alt: "Marina at evening" },
    "02-reading-the-market": { filename: "ch02-case.jpg", alt: "Yacht bows in a row" },
    "03-how-the-industry-works": { filename: "ch03-case.jpg", alt: "Yacht illuminated at night" },
    "04-acquisition-process": { filename: "ch04-case.jpg", alt: "Engine telegraph" },
    "05-new-build-versus-brokerage": { filename: "ch05-case.jpg", alt: "Hulls in the boat shed" },
    "06-refit": { filename: "ch06-case.jpg", alt: "Boathouses" },
    "07-operations": { filename: "ch07-case.jpg", alt: "At the helm" },
    "08-motor-versus-sail": { filename: "ch08-case.jpg", alt: "Square rig in monochrome" },
    "09-decision-framework": { filename: "ch09-case.jpg", alt: "Calm water sail" },
  },
  plates: {
    "01-reality-of-ownership": [
      { filename: "julia-taubitz-zAMUHlvftHA-unsplash.jpg", alt: "Chapter 01 plate" },
      { filename: "kateryna-hliznitsova-hm6BJObFpMI-unsplash.jpg", alt: "Chapter 01 plate" },
    ],
    "02-reading-the-market": [
      { filename: "kaleb-duperre-gGML8QtQ614-unsplash.jpg", alt: "Chapter 02 plate" },
      { filename: "kateryna-hliznitsova-nMo_EkEtYlM-unsplash.jpg", alt: "Chapter 02 plate" },
    ],
    "03-how-the-industry-works": [
      { filename: "karl-muscat-8S9DC-GerN0-unsplash.jpg", alt: "Chapter 03 plate" },
      { filename: "kateryna-hliznitsova-zSm1qBjYDcQ-unsplash.jpg", alt: "Chapter 03 plate" },
    ],
    "04-acquisition-process": [
      { filename: "karl-muscat-Pc85Zbj9K1Y-unsplash.jpg", alt: "Chapter 04 plate" },
      { filename: "katja-ano--dGT6BlPwNQ-unsplash.jpg", alt: "Chapter 04 plate" },
    ],
    "05-new-build-versus-brokerage": [
      { filename: "karl-paul-baldacchino-sWzRTyObW5Y-unsplash.jpg", alt: "Chapter 05 plate" },
      { filename: "kevs-XWNbUhUINB8-unsplash.jpg", alt: "Chapter 05 plate" },
    ],
    "06-refit": [
      { filename: "karsh-mehta-lzHT7mlT500-unsplash.jpg", alt: "Chapter 06 plate" },
      { filename: "kirsty-iPjaeaNq8Jw-unsplash.jpg", alt: "Chapter 06 plate" },
    ],
    "07-operations": [
      { filename: "kateryna-hliznitsova-2Ccv7o1a0UQ-unsplash.jpg", alt: "Chapter 07 plate" },
      { filename: "lakshmi-narasimha-lk7fFQnPMrM-unsplash.jpg", alt: "Chapter 07 plate" },
    ],
    "08-motor-versus-sail": [
      { filename: "kateryna-hliznitsova-FWA1DfzRq-A-unsplash.jpg", alt: "Chapter 08 plate" },
      { filename: "lazarescu-alexandra-I9XxRhaU6Ok-unsplash.jpg", alt: "Chapter 08 plate" },
    ],
    "09-decision-framework": [
      { filename: "kateryna-hliznitsova-UbNP8ygsNTw-unsplash.jpg", alt: "Chapter 09 plate" },
      { filename: "leo-talabardon-F9CdiSYF9Ys-unsplash.jpg", alt: "Chapter 09 plate" },
    ],
  },
  closing: { filename: "closing.jpg", alt: "Closing image" },
};
